# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: applications.azuread.upbound.io/v1beta2
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1beta1/application
  labels:
    testing.upbound.io/example-name: example
  name: reconciliation-test2
spec:
  forProvider:
    displayName: reconciliation-test2
