name: Publish Provider Artifacts

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "Branch name to use while publishing the packages (e.g. main)"
        default: ''
        required: false
      version:
        description: "Version string to use while publishing the packages (e.g. v1.0.0-alpha.1)"
        default: ''
        required: false

jobs:
  publish-service-artifacts:
    uses: sergenyalcin/provider-workflows/.github/workflows/publish-provider-non-family.yml@main
    with:
      branch_name: ${{ github.event.inputs.branch_name }}
      repository: provider-azuread
      version: ${{ github.event.inputs.version }}
      go-version: 1.23.6
      cleanup-disk: false
    secrets:
      GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}
      XPKG_UPBOUND_TOKEN: ${{ secrets.XPKG_UPBOUND_TOKEN }}
